name: Convert Notebooks to Python with Jupytext

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write  # Allows GitHub Actions to push changes

jobs:
  convert_notebooks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Jupytext
        run: |
          pip install jupytext

      - name: Convert Notebooks to Python Scripts
        run: |
          find . -name "*.ipynb" -exec jupytext --set-formats ipynb,py {} \;

      - name: Commit and Push Converted Files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --cached --quiet || git commit -m "Convert notebooks to Python scripts using Jupytext"
          git push